### PR TITLE
Binary Search Added In JavaScript

### PR DESCRIPTION
**Pull request by harry6003**
Binary Search is searching technique which works on Divide and Conquer approach. It used to search any element in a sorted array. 
As compared to linear, binary search is much faster with Time Complexity of O(logN) whereas linear search algorithm works in O(N) time complexity.

### CODE REVIEW

**Comment by harry6003** [comment]
Issue #59 Is solved. Please Review it and Merge for Hacktoberfest 2021

**Comment by harry6003** [comment]
Hey @SahanDisa Please Review my PR

**Comment by SahanDisa** [comment]
Kudos @harry6003! Welcome to SAG4X.

**Review by SahanDisa — APPROVED** [review]

**Comment by harry6003** [comment]
Thanks @SahanDisa ✔️❤️

**Pull request merged**
